server:
  port: 8081

spring:
  application:
    name: QUIZ-SERVICE #All microservices will have an unique name
  datasource:
    url: jdbc:mysql://localhost:3306/quiz_db
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    discovery:
      enabled: true

# Connect this eureka client with the eureka service registry
eureka:
  instance:
    hostname: localhost
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/